//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordCrackerServiceConsumer.Cracker {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://www.tempuri.org")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncryptedPasswordBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EncryptedPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EncryptedPasswordBase64 {
            get {
                return this.EncryptedPasswordBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedPasswordBase64Field, value) != true)) {
                    this.EncryptedPasswordBase64Field = value;
                    this.RaisePropertyChanged("EncryptedPasswordBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] EncryptedPassword {
            get {
                return this.EncryptedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedPasswordField, value) != true)) {
                    this.EncryptedPasswordField = value;
                    this.RaisePropertyChanged("EncryptedPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.tempuri.org", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoClearText", Namespace="http://www.tempuri.org")]
    [System.SerializableAttribute()]
    public partial class UserInfoClearText : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tempuri.org", ConfigurationName="Cracker.CrackerSoap")]
    public interface CrackerSoap {
        
        // CODEGEN: Generating message contract since element name GetPasswordListResult from namespace http://www.tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/GetPasswordList", ReplyAction="*")]
        PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse GetPasswordList(PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/GetPasswordList", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse> GetPasswordListAsync(PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest request);
        
        // CODEGEN: Generating message contract since element name GetDictionaryChunkResult from namespace http://www.tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/GetDictionaryChunk", ReplyAction="*")]
        PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse GetDictionaryChunk(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/GetDictionaryChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse> GetDictionaryChunkAsync(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/LogIt", ReplyAction="*")]
        void LogIt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/LogIt", ReplyAction="*")]
        System.Threading.Tasks.Task LogItAsync();
        
        // CODEGEN: Generating message contract since element name result from namespace http://www.tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/LogResults", ReplyAction="*")]
        PasswordCrackerServiceConsumer.Cracker.LogResultsResponse LogResults(PasswordCrackerServiceConsumer.Cracker.LogResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/LogResults", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.LogResultsResponse> LogResultsAsync(PasswordCrackerServiceConsumer.Cracker.LogResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPasswordList", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequestBody Body;
        
        public GetPasswordListRequest() {
        }
        
        public GetPasswordListRequest(PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPasswordListRequestBody {
        
        public GetPasswordListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPasswordListResponse", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponseBody Body;
        
        public GetPasswordListResponse() {
        }
        
        public GetPasswordListResponse(PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org")]
    public partial class GetPasswordListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfo> GetPasswordListResult;
        
        public GetPasswordListResponseBody() {
        }
        
        public GetPasswordListResponseBody(System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfo> GetPasswordListResult) {
            this.GetPasswordListResult = GetPasswordListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictionaryChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictionaryChunk", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequestBody Body;
        
        public GetDictionaryChunkRequest() {
        }
        
        public GetDictionaryChunkRequest(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictionaryChunkRequestBody {
        
        public GetDictionaryChunkRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictionaryChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictionaryChunkResponse", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponseBody Body;
        
        public GetDictionaryChunkResponse() {
        }
        
        public GetDictionaryChunkResponse(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org")]
    public partial class GetDictionaryChunkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.ArrayOfString GetDictionaryChunkResult;
        
        public GetDictionaryChunkResponseBody() {
        }
        
        public GetDictionaryChunkResponseBody(PasswordCrackerServiceConsumer.Cracker.ArrayOfString GetDictionaryChunkResult) {
            this.GetDictionaryChunkResult = GetDictionaryChunkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogResults", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.LogResultsRequestBody Body;
        
        public LogResultsRequest() {
        }
        
        public LogResultsRequest(PasswordCrackerServiceConsumer.Cracker.LogResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org")]
    public partial class LogResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfoClearText> result;
        
        public LogResultsRequestBody() {
        }
        
        public LogResultsRequestBody(System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfoClearText> result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogResultsResponse", Namespace="http://www.tempuri.org", Order=0)]
        public PasswordCrackerServiceConsumer.Cracker.LogResultsResponseBody Body;
        
        public LogResultsResponse() {
        }
        
        public LogResultsResponse(PasswordCrackerServiceConsumer.Cracker.LogResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogResultsResponseBody {
        
        public LogResultsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrackerSoapChannel : PasswordCrackerServiceConsumer.Cracker.CrackerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrackerSoapClient : System.ServiceModel.ClientBase<PasswordCrackerServiceConsumer.Cracker.CrackerSoap>, PasswordCrackerServiceConsumer.Cracker.CrackerSoap {
        
        public CrackerSoapClient() {
        }
        
        public CrackerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrackerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrackerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrackerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse PasswordCrackerServiceConsumer.Cracker.CrackerSoap.GetPasswordList(PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest request) {
            return base.Channel.GetPasswordList(request);
        }
        
        public System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfo> GetPasswordList() {
            PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest inValue = new PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequestBody();
            PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse retVal = ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).GetPasswordList(inValue);
            return retVal.Body.GetPasswordListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse> PasswordCrackerServiceConsumer.Cracker.CrackerSoap.GetPasswordListAsync(PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest request) {
            return base.Channel.GetPasswordListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetPasswordListResponse> GetPasswordListAsync() {
            PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest inValue = new PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.GetPasswordListRequestBody();
            return ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).GetPasswordListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse PasswordCrackerServiceConsumer.Cracker.CrackerSoap.GetDictionaryChunk(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest request) {
            return base.Channel.GetDictionaryChunk(request);
        }
        
        public PasswordCrackerServiceConsumer.Cracker.ArrayOfString GetDictionaryChunk() {
            PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest inValue = new PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequestBody();
            PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse retVal = ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).GetDictionaryChunk(inValue);
            return retVal.Body.GetDictionaryChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse> PasswordCrackerServiceConsumer.Cracker.CrackerSoap.GetDictionaryChunkAsync(PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest request) {
            return base.Channel.GetDictionaryChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkResponse> GetDictionaryChunkAsync() {
            PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest inValue = new PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.GetDictionaryChunkRequestBody();
            return ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).GetDictionaryChunkAsync(inValue);
        }
        
        public void LogIt() {
            base.Channel.LogIt();
        }
        
        public System.Threading.Tasks.Task LogItAsync() {
            return base.Channel.LogItAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordCrackerServiceConsumer.Cracker.LogResultsResponse PasswordCrackerServiceConsumer.Cracker.CrackerSoap.LogResults(PasswordCrackerServiceConsumer.Cracker.LogResultsRequest request) {
            return base.Channel.LogResults(request);
        }
        
        public void LogResults(System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfoClearText> result) {
            PasswordCrackerServiceConsumer.Cracker.LogResultsRequest inValue = new PasswordCrackerServiceConsumer.Cracker.LogResultsRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.LogResultsRequestBody();
            inValue.Body.result = result;
            PasswordCrackerServiceConsumer.Cracker.LogResultsResponse retVal = ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).LogResults(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.LogResultsResponse> PasswordCrackerServiceConsumer.Cracker.CrackerSoap.LogResultsAsync(PasswordCrackerServiceConsumer.Cracker.LogResultsRequest request) {
            return base.Channel.LogResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordCrackerServiceConsumer.Cracker.LogResultsResponse> LogResultsAsync(System.Collections.Generic.List<PasswordCrackerServiceConsumer.Cracker.UserInfoClearText> result) {
            PasswordCrackerServiceConsumer.Cracker.LogResultsRequest inValue = new PasswordCrackerServiceConsumer.Cracker.LogResultsRequest();
            inValue.Body = new PasswordCrackerServiceConsumer.Cracker.LogResultsRequestBody();
            inValue.Body.result = result;
            return ((PasswordCrackerServiceConsumer.Cracker.CrackerSoap)(this)).LogResultsAsync(inValue);
        }
    }
}
